# Generated by Django 5.2.2 on 2025-06-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='title',
        ),
    ]
