# Generated by Django 5.2.2 on 2025-06-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
